Constants =
  MIN_PASSWORD_BYTES: 8
  DEFAULT_PASSWORD_BYTES: 12
  KEY_DERIVATION_ALGORITHM:
    name: 'PBKDF2'
  KEY_DERIVATION_PERMISSIONS: ["deriveKey"]
  KEY_DERIVATION_ITERATIONS: 2048
  KEY_DERIVATION_HASH:
    name: 'SHA-256'
  ENCRYPTION_ALGORITHM:
    name: 'AES-GCM'
    length: 256
  ENCRYPTION_PERMISSIONS: ["encrypt", "decrypt"]
  ENCRYPTION_AUTH_TAG_LENGTH: 128
  SALT_BYTES: 8

module.exports = Constants
