Constants =
  MIN_PASSWORD_BYTES: 8
  KEY_DERIVATION_ALGORITHM:
    name: 'PBKDF2'
  KEY_DERIVATION_PERMISSIONS: ["deriveKey"]
  KEY_DERIVATION_ITERATIONS: 2048
  KEY_DERIVATION_HASH:
    name: 'SHA-256'
  ENCRYPTION_KEY_ALGORITHM:
    name: 'AES-GCM'
    length: 256
  ENCRYPTION_KEY_PERMISSIONS: ["encrypt", "decrypt"]

module.exports = Constants
