Constants =
  MIN_PASSWORD_BYTES: 8
  DEFAULT_PASSWORD_BYTES: 16
  KEY_DERIVATION_ALGORITHM:
    name: 'PBKDF2'
  KEY_DERIVATION_PERMISSIONS: ["deriveKey"]
  KEY_DERIVATION_ITERATIONS: 1000000
  KEY_DERIVATION_HASH:
    name: 'SHA-256'
  ENCRYPTION_ALGORITHM:
    name: 'AES-GCM'
    length: 256
  ENCRYPTION_PERMISSIONS: ["encrypt", "decrypt"]
  ENCRYPTION_AUTH_TAG_LENGTH: 128
  ONE_TIME_CODE_DIGITS: 8
  SALT_BYTES: 16
  TEMPORARY_PASSWORD_VALIDITY_MS: 30000

module.exports = Constants
